// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxHQzv-z3TFfqFaS0Ks98ODp9izDcDKMU',
    appId: '1:337272009893:android:f2c14120e0161425f1494c',
    messagingSenderId: '337272009893',
    projectId: 'campuscharcha-2',
    databaseURL: 'https://campuscharcha-2-default-rtdb.firebaseio.com',
    storageBucket: 'campuscharcha-2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV8rz2cLQCXdeOaD4nVzic4auXNqzGLP0',
    appId: '1:337272009893:web:61668e61dd43bfbff1494c',
    messagingSenderId: '337272009893',
    projectId: 'campuscharcha-2',
    authDomain: 'campuscharcha-2.firebaseapp.com',
    databaseURL: 'https://campuscharcha-2-default-rtdb.firebaseio.com',
    storageBucket: 'campuscharcha-2.firebasestorage.app',
  );

}