// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxHQzv-z3TFfqFaS0Ks98ODp9izDcDKMU',
    appId: '1:337272009893:android:fdfcebffdcf23b0bf1494c',
    messagingSenderId: '337272009893',
    projectId: 'campuscharcha-2',
    databaseURL: 'https://campuscharcha-2-default-rtdb.firebaseio.com',
    storageBucket: 'campuscharcha-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHXU3MlyCo0jIVV-JvDYCef4kk91MYUPU',
    appId: '1:337272009893:ios:792ccb56a6ac2f5ff1494c',
    messagingSenderId: '337272009893',
    projectId: 'campuscharcha-2',
    databaseURL: 'https://campuscharcha-2-default-rtdb.firebaseio.com',
    storageBucket: 'campuscharcha-2.firebasestorage.app',
    iosBundleId: 'com.campus.app',
  );
}
